services:
  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "RockyRock@1"]

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
      ME_CONFIG_SITE_BASEURL: /mongo-admin/
    depends_on:
      - mongo

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: python_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ../adapters:/app/adapters
      - ../api:/app/api
      - ../database:/app/database
      - ../diagrams:/app/diagrams
      - ../fsm:/app/fsm
      - ../Scripts:/app/Scripts
      - ../storage:/app/storage
      - ../workflow_builder:/app/workflow_builder
      - ../config.py:/app/config.py
      - ../context.py:/app/context.py
      - ../main.py:/app/main.py
      - ../utils.py:/app/utils.py
    restart: always

volumes:
  redis_data:
  mongo_data: