services:
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"  # accessible only from host
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "RockyRock@1"]
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "8080:80"

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
